# Generated by Django 3.2.3 on 2021-07-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingimage',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='weddingvideo',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='weddingvideo',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
