# Generated by Django 3.2.3 on 2021-05-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_full',
        ),
        migrations.AddField(
            model_name='product',
            name='price_progress',
            field=models.FloatField(default=0),
        ),
    ]
