# Generated by Django 3.2.3 on 2021-05-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_wishlist', '0003_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_self_buy',
            field=models.BooleanField(default=False),
        ),
    ]
